// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122233852_AddCoordinadorSeparado")]
    partial class AddCoordinadorSeparado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auth.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a4721-233e-78b7-b7af-c71a11a344e4"),
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = new Guid("072de9db-ea58-418f-a43d-39f846821b4e"),
                            Name = "Digitalizador",
                            NormalizedName = "DIGITALIZADOR"
                        });
                });

            modelBuilder.Entity("Domain.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("\"PersonaId\" IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96cb56e3-def8-4433-8341-ecf5424c7a7f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16de0733-137a-4fa7-b65e-7bfc548e2be3",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAKqLP59ArNX3MAlKYFmKMlc2Rc8QJDlgQL/CWRVH63Cg4Z1JYLKTP9BTUeJOTnMuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d21bd88e-7f24-4fb9-b9f2-34924342ef90",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.Barrio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("barrio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Barrio 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Barrio 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Barrio 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Barrio 4"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Maximo")
                        .HasColumnType("integer");

                    b.Property<int>("Minimo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Maximo = 9,
                            Minimo = 0,
                            Nombre = "Grupo A"
                        },
                        new
                        {
                            Id = 2,
                            Maximo = 15,
                            Minimo = 10,
                            Nombre = "Grupo B"
                        },
                        new
                        {
                            Id = 3,
                            Maximo = 30,
                            Minimo = 16,
                            Nombre = "Grupo C"
                        },
                        new
                        {
                            Id = 4,
                            Maximo = 60,
                            Minimo = 31,
                            Nombre = "Grupo D"
                        },
                        new
                        {
                            Id = 5,
                            Maximo = 100,
                            Minimo = 61,
                            Nombre = "Grupo E"
                        },
                        new
                        {
                            Id = 6,
                            Maximo = 300,
                            Minimo = 101,
                            Nombre = "Grupo F"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.CodigoB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("codigo_b", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "CodigoB 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CodigoB 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CodigoB 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CodigoB 4"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.CodigoC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("codigo_c", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "CodigoC 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "CodigoC 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CodigoC 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "CodigoC 4"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.Lengua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("lengua", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Lengua 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Lengua 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Lengua 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Lengua 4"
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.MesaVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PuestoVotacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PuestoVotacionId");

                    b.ToTable("mesa_votacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Mesa 1",
                            PuestoVotacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mesa 2",
                            PuestoVotacionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mesa 3",
                            PuestoVotacionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Mesa 4",
                            PuestoVotacionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Mesa 1",
                            PuestoVotacionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Mesa 2",
                            PuestoVotacionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Mesa 3",
                            PuestoVotacionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Mesa 4",
                            PuestoVotacionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Mesa 1",
                            PuestoVotacionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Mesa 2",
                            PuestoVotacionId = 3
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Mesa 3",
                            PuestoVotacionId = 3
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Mesa 4",
                            PuestoVotacionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Mesa 1",
                            PuestoVotacionId = 4
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Mesa 2",
                            PuestoVotacionId = 4
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Mesa 3",
                            PuestoVotacionId = 4
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Mesa 4",
                            PuestoVotacionId = 4
                        });
                });

            modelBuilder.Entity("Domain.Catalogos.PuestoVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("puesto_votacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "PuestoVotacion 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "PuestoVotacion 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PuestoVotacion 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "PuestoVotacion 4"
                        });
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Apodo")
                        .HasColumnType("text");

                    b.Property<int?>("BarrioId")
                        .HasColumnType("integer");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CodigoCId")
                        .HasColumnType("integer");

                    b.Property<int?>("CoordinadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Familia")
                        .HasColumnType("text");

                    b.Property<bool>("IsCoordinador")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLider")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int?>("LiderId")
                        .HasColumnType("integer");

                    b.Property<int>("MesaVotacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BarrioId");

                    b.HasIndex("CodigoCId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("LiderId");

                    b.HasIndex("MesaVotacionId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Domain.Personas.PersonaCodigoB", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoBId")
                        .HasColumnType("integer");

                    b.HasKey("PersonaId", "CodigoBId");

                    b.HasIndex("CodigoBId");

                    b.ToTable("PersonaCodigoB");
                });

            modelBuilder.Entity("Domain.Personas.PersonaLengua", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<int>("LenguaId")
                        .HasColumnType("integer");

                    b.HasKey("PersonaId", "LenguaId");

                    b.HasIndex("LenguaId");

                    b.ToTable("PersonasLengua");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("96cb56e3-def8-4433-8341-ecf5424c7a7f"),
                            RoleId = new Guid("019a4721-233e-78b7-b7af-c71a11a344e4")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_token", (string)null);
                });

            modelBuilder.Entity("Domain.Auth.AppUser", b =>
                {
                    b.HasOne("Domain.Personas.Persona", "Persona")
                        .WithOne("User")
                        .HasForeignKey("Domain.Auth.AppUser", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_user_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Catalogos.MesaVotacion", b =>
                {
                    b.HasOne("Domain.Catalogos.PuestoVotacion", "PuestoVotacion")
                        .WithMany("MesasVotacion")
                        .HasForeignKey("PuestoVotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuestoVotacion");
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.HasOne("Domain.Catalogos.Barrio", "Barrio")
                        .WithMany("Personas")
                        .HasForeignKey("BarrioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Catalogos.CodigoC", "CodigoC")
                        .WithMany("Personas")
                        .HasForeignKey("CodigoCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Personas.Persona", "Coordinador")
                        .WithMany("Coordinados")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Personas.Persona", "Lider")
                        .WithMany("PersonasACargo")
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Catalogos.MesaVotacion", "MesaVotacion")
                        .WithMany("Personas")
                        .HasForeignKey("MesaVotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barrio");

                    b.Navigation("CodigoC");

                    b.Navigation("Coordinador");

                    b.Navigation("Lider");

                    b.Navigation("MesaVotacion");
                });

            modelBuilder.Entity("Domain.Personas.PersonaCodigoB", b =>
                {
                    b.HasOne("Domain.Catalogos.CodigoB", "CodigoB")
                        .WithMany("PersonasCodigoB")
                        .HasForeignKey("CodigoBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Personas.Persona", "Persona")
                        .WithMany("CodigosB")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoB");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Personas.PersonaLengua", b =>
                {
                    b.HasOne("Domain.Catalogos.Lengua", "Lengua")
                        .WithMany("PersonasLengua")
                        .HasForeignKey("LenguaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Personas.Persona", "Persona")
                        .WithMany("Lenguas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lengua");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Auth.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Domain.Auth.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Catalogos.Barrio", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Domain.Catalogos.CodigoB", b =>
                {
                    b.Navigation("PersonasCodigoB");
                });

            modelBuilder.Entity("Domain.Catalogos.CodigoC", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Domain.Catalogos.Lengua", b =>
                {
                    b.Navigation("PersonasLengua");
                });

            modelBuilder.Entity("Domain.Catalogos.MesaVotacion", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Domain.Catalogos.PuestoVotacion", b =>
                {
                    b.Navigation("MesasVotacion");
                });

            modelBuilder.Entity("Domain.Personas.Persona", b =>
                {
                    b.Navigation("CodigosB");

                    b.Navigation("Coordinados");

                    b.Navigation("Lenguas");

                    b.Navigation("PersonasACargo");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
